#!/usr/bin/env bash
set -euo pipefail

mkdir -p /var/lib/redalibabaclaude

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/alibaba" ]]; then
  install -m 755 -o root -g root "$SCRIPT_DIR/alibaba" /usr/local/bin/alibaba
fi

if [[ ! -d /opt/redalibabaclaude/.venv ]]; then
  /usr/bin/python3 -m venv /opt/redalibabaclaude/.venv
fi

/opt/redalibabaclaude/.venv/bin/pip install --upgrade pip >/dev/null
/opt/redalibabaclaude/.venv/bin/pip install -r /opt/redalibabaclaude/requirements.txt >/dev/null

if [[ -f /etc/redalibabaclaude.env ]]; then
  # Preserve live keys on redeploy. Key rotation is done with /usr/local/bin/alibaba.
  REDALIBABACLAUDE_SG_API_KEY="$(grep -E '^REDALIBABACLAUDE_SG_API_KEY=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_US_API_KEY="$(grep -E '^REDALIBABACLAUDE_US_API_KEY=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_EXPERIMENTAL_THINKING_BLOCKS="$(grep -E '^REDALIBABACLAUDE_EXPERIMENTAL_THINKING_BLOCKS=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_FAKE_THINKING_SIGNATURE_PREFIX="$(grep -E '^REDALIBABACLAUDE_FAKE_THINKING_SIGNATURE_PREFIX=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_FORCE_ANTHROPIC_THINKING="$(grep -E '^REDALIBABACLAUDE_FORCE_ANTHROPIC_THINKING=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_WEBSEARCH_INTERNALIZE_STREAM_REQUESTS="$(grep -E '^REDALIBABACLAUDE_WEBSEARCH_INTERNALIZE_STREAM_REQUESTS=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_TOOL_REPAIR_MAX_ROUNDS="$(grep -E '^REDALIBABACLAUDE_TOOL_REPAIR_MAX_ROUNDS=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_DATA_DIR="$(grep -E '^REDALIBABACLAUDE_DATA_DIR=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_TOKEN_METRICS_ENABLED="$(grep -E '^REDALIBABACLAUDE_TOKEN_METRICS_ENABLED=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_TOKEN_METRICS_DB="$(grep -E '^REDALIBABACLAUDE_TOKEN_METRICS_DB=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_TOKEN_METRICS_QUEUE_SIZE="$(grep -E '^REDALIBABACLAUDE_TOKEN_METRICS_QUEUE_SIZE=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
  REDALIBABACLAUDE_TOKEN_METRICS_RECENT_LIMIT="$(grep -E '^REDALIBABACLAUDE_TOKEN_METRICS_RECENT_LIMIT=' /etc/redalibabaclaude.env | tail -n 1 | cut -d= -f2- || true)"
fi

: "${REDALIBABACLAUDE_SG_API_KEY:=}"
: "${REDALIBABACLAUDE_US_API_KEY:=}"
: "${REDALIBABACLAUDE_DATA_DIR:=/var/lib/redalibabaclaude}"
: "${REDALIBABACLAUDE_TOKEN_METRICS_ENABLED:=1}"
: "${REDALIBABACLAUDE_TOKEN_METRICS_DB:=${REDALIBABACLAUDE_DATA_DIR}/token_usage.sqlite3}"
: "${REDALIBABACLAUDE_TOKEN_METRICS_QUEUE_SIZE:=10000}"
: "${REDALIBABACLAUDE_TOKEN_METRICS_RECENT_LIMIT:=80}"

mkdir -p "$REDALIBABACLAUDE_DATA_DIR"

cat > /etc/redalibabaclaude.env <<EOF
REDALIBABACLAUDE_HOST=0.0.0.0
REDALIBABACLAUDE_PORT=5052
REDALIBABACLAUDE_SG_BASE_URL=https://dashscope-intl.aliyuncs.com/compatible-mode/v1
REDALIBABACLAUDE_US_BASE_URL=https://dashscope-us.aliyuncs.com/compatible-mode/v1
REDALIBABACLAUDE_SG_API_KEY=${REDALIBABACLAUDE_SG_API_KEY}
REDALIBABACLAUDE_US_API_KEY=${REDALIBABACLAUDE_US_API_KEY}
REDALIBABACLAUDE_REQUIRE_AUTH=1
REDALIBABACLAUDE_AUTH_TOKENS=red
REDALIBABACLAUDE_DEFAULT_MODEL=Qwen Coder Plus
REDALIBABACLAUDE_STREAM_CHUNK_SIZE=1
REDALIBABACLAUDE_CONNECT_TIMEOUT=20
REDALIBABACLAUDE_READ_TIMEOUT=360
REDALIBABACLAUDE_MAX_OUTPUT_TOKENS=${REDALIBABACLAUDE_MAX_OUTPUT_TOKENS:-8192}
REDALIBABACLAUDE_WEBSEARCH_FALLBACK_ENABLED=${REDALIBABACLAUDE_WEBSEARCH_FALLBACK_ENABLED:-1}
REDALIBABACLAUDE_WEBSEARCH_FALLBACK_URL=${REDALIBABACLAUDE_WEBSEARCH_FALLBACK_URL:-http://127.0.0.1:8088/search}
REDALIBABACLAUDE_WEBSEARCH_FALLBACK_MAX_RESULTS=${REDALIBABACLAUDE_WEBSEARCH_FALLBACK_MAX_RESULTS:-5}
REDALIBABACLAUDE_WEBSEARCH_FALLBACK_MAX_QUERIES=${REDALIBABACLAUDE_WEBSEARCH_FALLBACK_MAX_QUERIES:-3}
REDALIBABACLAUDE_WEBSEARCH_FALLBACK_TIMEOUT=${REDALIBABACLAUDE_WEBSEARCH_FALLBACK_TIMEOUT:-8}
REDALIBABACLAUDE_WEBSEARCH_FALLBACK_LANGUAGE=${REDALIBABACLAUDE_WEBSEARCH_FALLBACK_LANGUAGE:-pt-BR}
REDALIBABACLAUDE_WEBSEARCH_INTERNAL_MAX_ROUNDS=${REDALIBABACLAUDE_WEBSEARCH_INTERNAL_MAX_ROUNDS:-2}
REDALIBABACLAUDE_WEBSEARCH_INTERNALIZE_STREAM_REQUESTS=${REDALIBABACLAUDE_WEBSEARCH_INTERNALIZE_STREAM_REQUESTS:-0}
REDALIBABACLAUDE_TOOL_REPAIR_MAX_ROUNDS=${REDALIBABACLAUDE_TOOL_REPAIR_MAX_ROUNDS:-3}
REDALIBABACLAUDE_DATA_DIR=${REDALIBABACLAUDE_DATA_DIR}
REDALIBABACLAUDE_TOKEN_METRICS_ENABLED=${REDALIBABACLAUDE_TOKEN_METRICS_ENABLED}
REDALIBABACLAUDE_TOKEN_METRICS_DB=${REDALIBABACLAUDE_TOKEN_METRICS_DB}
REDALIBABACLAUDE_TOKEN_METRICS_QUEUE_SIZE=${REDALIBABACLAUDE_TOKEN_METRICS_QUEUE_SIZE}
REDALIBABACLAUDE_TOKEN_METRICS_RECENT_LIMIT=${REDALIBABACLAUDE_TOKEN_METRICS_RECENT_LIMIT}
REDALIBABACLAUDE_RATE_LIMIT_MIN_INTERVAL_SECONDS=1
REDALIBABACLAUDE_RATE_LIMIT_COOLDOWN_SECONDS=12
REDALIBABACLAUDE_RATE_LIMIT_COOLDOWN_STEP_SECONDS=4
REDALIBABACLAUDE_RATE_LIMIT_MAX_COOLDOWN_SECONDS=45
REDALIBABACLAUDE_MAX_429_RETRIES=6
REDALIBABACLAUDE_SERVER_ERROR_COOLDOWN_SECONDS=4
REDALIBABACLAUDE_MAX_5XX_RETRIES=4
REDALIBABACLAUDE_EXPERIMENTAL_THINKING_BLOCKS=${REDALIBABACLAUDE_EXPERIMENTAL_THINKING_BLOCKS:-1}
REDALIBABACLAUDE_FAKE_THINKING_SIGNATURE_PREFIX=${REDALIBABACLAUDE_FAKE_THINKING_SIGNATURE_PREFIX:-redalibaba}
REDALIBABACLAUDE_FORCE_ANTHROPIC_THINKING=${REDALIBABACLAUDE_FORCE_ANTHROPIC_THINKING:-1}
REDALIBABACLAUDE_TLS_CERT=/etc/letsencrypt/live/redsystems.ddns.net/fullchain.pem
REDALIBABACLAUDE_TLS_KEY=/etc/letsencrypt/live/redsystems.ddns.net/privkey.pem
EOF

sed -i 's/\r$//' \
  /etc/systemd/system/redalibabaclaude.service \
  /etc/redalibabaclaude.env \
  /opt/redalibabaclaude/app.py \
  /opt/redalibabaclaude/requirements.txt \
  /opt/redalibabaclaude/README.md \
  /opt/redalibabaclaude/tests/test_app.py

/usr/bin/python3 -m py_compile /opt/redalibabaclaude/app.py /opt/redalibabaclaude/tests/test_app.py
(cd /opt/redalibabaclaude && ./.venv/bin/python -m unittest discover -s tests -v)

ufw allow 5052/tcp
systemctl daemon-reload
systemctl enable --now redalibabaclaude.service
systemctl restart redalibabaclaude.service
sleep 2
systemctl is-active redalibabaclaude.service
ss -tlnp | grep ':5052 '
