const DEFAULT_CONFIG = {
  app: {
    name: "REDIA",
    host: process.env.REDIA_HOST || "0.0.0.0",
    port: parseInt(process.env.REDIA_PORT || "3099", 10),
  },
  proxy: {
    base_url: process.env.REDIA_PROXY_URL || "http://redsystems.ddns.net:8080",
    timeout_ms: 90000,
  },
  chat: {
    enabled: true,
    default_model: process.env.REDIA_DEFAULT_MODEL || "",
    fallback_models: [],
    vision_model: process.env.REDIA_VISION_MODEL || "",
    temperature: 0.82,
    max_context_messages: 24,
    max_context_chars: 12000,
    group_prefix: "red",
    private_mode: "always",
    group_mode: "prefix_or_mention",
    system_prompt: [
      "Voce e a REDIA, uma inteligencia artificial integrada ao WhatsApp.",
      "Fale em portugues do Brasil de forma natural, humana, direta e presente.",
      "Nao use tom corporativo, nao explique que esta processando e nao force listas.",
      "Adapte seu tamanho de resposta ao momento: as vezes curto, as vezes mais completo.",
      "Em grupos, participe com bom senso e nao monopolize a conversa.",
    ].join(" "),
  },
  streaming: {
    enabled: true,
    edit_first_message: true,
    initial_text: "...",
    min_update_ms: 850,
    min_update_chars: 80,
  },
  learning: {
    enabled: true,
    model: process.env.REDIA_LEARNING_MODEL || "",
    summarize_after_messages: 18,
    min_conversation_messages: 8,
    batch_messages: 8,
    analysis_window_messages: 28,
    keep_recent_messages: 10,
    memory_facts_per_contact: 12,
    max_memory_facts_per_run: 6,
    cooldown_ms: 120000,
    min_interval_ms: 120000,
  },
  proactive: {
    enabled: true,
    model: process.env.REDIA_PROACTIVE_MODEL || "",
    realtime_enabled: true,
    frequency: 0.16,
    cooldown_ms: 45000,
    active_group_threshold: 5,
    active_group_window_ms: 120000,
  },
  media: {
    audio_required: true,
    image_required: true,
    documents_enabled: true,
    max_image_bytes: 1200000,
  },
  image_generation: {
    enabled: true,
    provider: "kaggle_worker",
    worker_token: process.env.REDIA_IMAGE_WORKER_TOKEN || "",
    prompt_model: process.env.REDIA_IMAGE_PROMPT_MODEL || "",
    ack_text: "Vou gerar uma imagem e te mando aqui quando ficar pronta.",
    blocked_text: "Nao vou gerar imagem sexual explicita, pessoa real, menor/aparencia jovem, deepfake ou nudez a partir de foto enviada. Posso fazer uma versao ficcional nao explicita.",
    max_pending_jobs: 20,
    default_profile: "sdxl_lightning",
    default_width: 768,
    default_height: 768,
    default_steps: 4,
    default_cfg: 0.0,
  },
  stt: {
    enabled: true,
    provider: process.env.REDIA_STT_PROVIDER || "groq",
    api_key: process.env.GROQ_API_KEY || process.env.OPENAI_API_KEY || "",
    model: "whisper-large-v3-turbo",
    language: "pt",
  },
  tts: {
    enabled: String(process.env.REDIA_TTS_ENABLED || "true") === "true",
    audio_probability: parseFloat(process.env.REDIA_TTS_AUDIO_PROBABILITY || "0.12"),
    voice: process.env.REDIA_TTS_VOICE || "pt-BR-FranciscaNeural",
    rate: process.env.REDIA_TTS_RATE || "-5%",
    pitch: process.env.REDIA_TTS_PITCH || "+0Hz",
    volume: process.env.REDIA_TTS_VOLUME || "+0%",
    max_chars: 520,
  },
  whatsapp: {
    auto_start: true,
    auth_dir: "",
    mark_read: true,
    typing_presence: true,
    ignore_old_messages_ms: 120000,
  },
  dashboard: {
    enabled: true,
  },
};

module.exports = { DEFAULT_CONFIG };
