use_default_settings: true

general:
  debug: false
  instance_name: "RED Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "pt-BR"
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  base_url: "http://redsystems.ddns.net/search/"
  secret_key: "change-me-before-production"
  limiter: false
  public_instance: false
  image_proxy: true
  method: "GET"

ui:
  static_use_hash: true
  default_locale: "pt-BR"
  query_in_title: true

valkey:
  url: redis://valkey:6379/0

outgoing:
  request_timeout: 4.0
  max_request_timeout: 10.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
