// STADIA — mock data (no real brands, fictional teams + product names)

const TEAMS = [
  { code: "VLT", name: "Volturi FC", colors: ["#0b0d12", "#c8ff00"] },
  { code: "MTR", name: "Meteora SC", colors: ["#1a1f3b", "#ff4566"] },
  { code: "ARK", name: "Arktos United", colors: ["#0e2a26", "#00e5a0"] },
  { code: "ORS", name: "Orsa Athletic", colors: ["#311b45", "#7c5cff"] },
  { code: "RVN", name: "Ravena Norte", colors: ["#1d1d1d", "#ffb020"] },
  { code: "KNT", name: "Kentaro 09", colors: ["#22050b", "#ff7a18"] },
];

const CATEGORIES = [
  { id: "camisas", name: "Camisas", count: 184, icon: "shirt" },
  { id: "chuteiras", name: "Chuteiras", count: 96, icon: "boot" },
  { id: "treino", name: "Treino", count: 312, icon: "dumbbell" },
  { id: "bolas", name: "Bolas", count: 42, icon: "ball" },
  { id: "acessorios", name: "Acessórios", count: 156, icon: "tag" },
  { id: "femme", name: "Coleção Femme", count: 88, icon: "spark" },
];

const PRODUCTS = [
  {
    id: "p01",
    slug: "camisa-volturi-home-26",
    name: "Camisa Volturi Home 26",
    sub: "Kit Oficial · Temporada 25/26",
    category: "camisas",
    team: "VLT",
    price: 449.9,
    listPrice: 499.9,
    rating: 4.8,
    reviews: 1284,
    badge: "drop",
    colors: [
      { name: "Onyx", hex: "#0b0d12" },
      { name: "Volt", hex: "#c8ff00" },
    ],
    sizes: ["P", "M", "G", "GG", "XGG"],
    stock: 42,
    imageBg: "linear-gradient(160deg,#0b0d12,#1f2933 60%,#c8ff00 220%)",
    imageLabel: "kit volturi 26",
    materials: "Tecido AeroDry · 92% poliamida reciclada",
    drop: "MATCHDAY 03",
    tags: ["NEW", "OFICIAL"],
    desc: "Camisa principal do Volturi FC para a temporada 25/26. Construção em tricot AeroDry com canais de ventilação no dorso e gola tricotada com inscrição da torcida.",
  },
  {
    id: "p02",
    slug: "chuteira-arktos-hyperblade",
    name: "Arktos HyperBlade FG",
    sub: "Chuteira de campo · Pro series",
    category: "chuteiras",
    team: "ARK",
    price: 1299.0,
    listPrice: 1499.0,
    rating: 4.9,
    reviews: 432,
    badge: "elite",
    colors: [
      { name: "Glacier", hex: "#0e2a26" },
      { name: "Sun", hex: "#ffb020" },
    ],
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    stock: 14,
    imageBg: "linear-gradient(140deg,#021412,#0e2a26 50%,#00e5a0 200%)",
    imageLabel: "chuteira hyperblade",
    materials: "Cabedal Knit Cage · solado FG titanium",
    drop: "ARKTOS PRO",
    tags: ["PRO"],
    desc: "Chuteira de alta performance com cabedal Knit Cage e travas FG forjadas em alumínio aeroespacial. Reduz o peso em 18% sem comprometer estabilidade.",
  },
  {
    id: "p03",
    slug: "bola-orsa-radar-pro",
    name: "Orsa Radar Pro",
    sub: "Bola oficial · FIFA Quality",
    category: "bolas",
    team: "ORS",
    price: 599.0,
    listPrice: 599.0,
    rating: 4.7,
    reviews: 312,
    badge: null,
    colors: [
      { name: "Vapor", hex: "#7c5cff" },
      { name: "Onyx", hex: "#0a0a12" },
    ],
    sizes: ["#5"],
    stock: 89,
    imageBg: "radial-gradient(circle at 30% 30%,#a78cff,#311b45 60%,#0a0a12)",
    imageLabel: "bola radar pro",
    materials: "Termo-soldada · 12 painéis",
    drop: "RADAR LINE",
    tags: ["FIFA"],
    desc: "Bola termo-soldada de 12 painéis com câmara de látex pressurizado. Trajetória previsível em alta velocidade.",
  },
  {
    id: "p04",
    slug: "regata-treino-meteora",
    name: "Regata Meteora Train",
    sub: "Treino · Quick-dry",
    category: "treino",
    team: "MTR",
    price: 189.9,
    listPrice: 219.9,
    rating: 4.6,
    reviews: 521,
    badge: "deal",
    colors: [
      { name: "Crimson", hex: "#ff4566" },
      { name: "Onyx", hex: "#1a1f3b" },
    ],
    sizes: ["P", "M", "G", "GG"],
    stock: 120,
    imageBg: "linear-gradient(170deg,#1a1f3b,#ff4566 200%)",
    imageLabel: "regata meteora",
    desc: "Regata em malha micro-perfurada com painel reflexivo. Caimento fluido, ideal para treinos de alta intensidade.",
  },
  {
    id: "p05",
    slug: "shorts-ravena-cargo",
    name: "Ravena Cargo Tech",
    sub: "Shorts utility · Stretch",
    category: "treino",
    team: "RVN",
    price: 259.0,
    listPrice: 259.0,
    rating: 4.5,
    reviews: 188,
    badge: "new",
    colors: [
      { name: "Stone", hex: "#3a3a3a" },
      { name: "Sand", hex: "#c0a87c" },
    ],
    sizes: ["P", "M", "G", "GG"],
    stock: 65,
    imageBg: "linear-gradient(160deg,#1d1d1d,#3a3a3a 50%,#ffb020 220%)",
    imageLabel: "shorts ravena",
    desc: "Shorts cargo com 4-way stretch e bolsos magnéticos. Tecido tratado com repelente DWR.",
  },
  {
    id: "p06",
    slug: "meiao-stadia-pro",
    name: "Meião STADIA Pro",
    sub: "Compressão graduada",
    category: "acessorios",
    team: null,
    price: 89.9,
    listPrice: 99.9,
    rating: 4.7,
    reviews: 942,
    badge: null,
    colors: [
      { name: "Onyx", hex: "#0a0a0a" },
      { name: "Volt", hex: "#c8ff00" },
      { name: "White", hex: "#f5f5f5" },
    ],
    sizes: ["35-38", "39-42", "43-46"],
    stock: 220,
    imageBg: "linear-gradient(180deg,#0a0a0a,#1c1c1c)",
    imageLabel: "meiao pro",
    desc: "Meiões de compressão graduada com reforço no calcanhar e dorso. Alta retorno venoso em jogos longos.",
  },
  {
    id: "p07",
    slug: "luva-kentaro-blocker",
    name: "Kentaro Blocker GK",
    sub: "Luva goleiro · Pro grip",
    category: "acessorios",
    team: "KNT",
    price: 549.0,
    listPrice: 549.0,
    rating: 4.8,
    reviews: 156,
    badge: "elite",
    colors: [
      { name: "Inferno", hex: "#22050b" },
      { name: "Lava", hex: "#ff7a18" },
    ],
    sizes: ["8", "9", "10", "11"],
    stock: 22,
    imageBg: "linear-gradient(140deg,#22050b,#ff7a18 200%)",
    imageLabel: "luva blocker",
    desc: "Luva profissional com palma em látex Contact Pro 4mm. Punho com fechamento bandage de fixação total.",
  },
  {
    id: "p08",
    slug: "jaqueta-windrunner-vlt",
    name: "Volturi Windrunner",
    sub: "Jaqueta corta-vento",
    category: "treino",
    team: "VLT",
    price: 699.0,
    listPrice: 799.0,
    rating: 4.6,
    reviews: 244,
    badge: "drop",
    colors: [
      { name: "Onyx", hex: "#0b0d12" },
      { name: "Volt", hex: "#c8ff00" },
    ],
    sizes: ["P", "M", "G", "GG"],
    stock: 38,
    imageBg: "linear-gradient(150deg,#0b0d12,#1f2933 60%,#c8ff00 230%)",
    imageLabel: "jaqueta windrunner",
    desc: "Casaco corta-vento ultra-leve com costuras seladas. Capuz ajustável e bolso de ventilação dorsal.",
  },
  {
    id: "p09",
    slug: "mochila-stadia-matchday",
    name: "STADIA Matchday 28L",
    sub: "Mochila técnica",
    category: "acessorios",
    team: null,
    price: 459.0,
    listPrice: 459.0,
    rating: 4.9,
    reviews: 318,
    badge: null,
    colors: [{ name: "Onyx", hex: "#0a0a0a" }],
    sizes: ["28L"],
    stock: 41,
    imageBg: "linear-gradient(170deg,#0a0a0a,#1c1c1c 60%,#7c5cff 240%)",
    imageLabel: "mochila matchday",
    desc: "Mochila com compartimento isolado para chuteiras, bolso para notebook 16\" e tiras MOLLE.",
  },
  {
    id: "p10",
    slug: "camisa-meteora-away",
    name: "Camisa Meteora Away 26",
    sub: "Kit Oficial · Visitante",
    category: "camisas",
    team: "MTR",
    price: 449.9,
    listPrice: 449.9,
    rating: 4.7,
    reviews: 612,
    badge: "new",
    colors: [
      { name: "Crimson", hex: "#ff4566" },
      { name: "Night", hex: "#1a1f3b" },
    ],
    sizes: ["P", "M", "G", "GG", "XGG"],
    stock: 76,
    imageBg: "linear-gradient(160deg,#1a1f3b,#ff4566 220%)",
    imageLabel: "kit meteora 26",
    desc: "Camisa visitante do Meteora SC para a temporada 25/26. Construção em malha AeroDry com gradiente sublimado.",
  },
  {
    id: "p11",
    slug: "boné-arktos-curve",
    name: "Arktos Curve Cap",
    sub: "Boné estruturado",
    category: "acessorios",
    team: "ARK",
    price: 149.0,
    listPrice: 149.0,
    rating: 4.5,
    reviews: 87,
    badge: null,
    colors: [
      { name: "Glacier", hex: "#0e2a26" },
      { name: "Mint", hex: "#00e5a0" },
    ],
    sizes: ["único"],
    stock: 92,
    imageBg: "linear-gradient(150deg,#0e2a26,#00e5a0 240%)",
    imageLabel: "bone curve",
    desc: "Boné de 6 painéis com aba curva pré-formada. Patch tecido frontal e bordado posterior.",
  },
  {
    id: "p12",
    slug: "camisa-femme-orsa",
    name: "Camisa Orsa Femme 26",
    sub: "Coleção Femme · Modelagem feminina",
    category: "femme",
    team: "ORS",
    price: 449.9,
    listPrice: 449.9,
    rating: 4.8,
    reviews: 198,
    badge: "drop",
    colors: [
      { name: "Vapor", hex: "#7c5cff" },
      { name: "Onyx", hex: "#0a0a12" },
    ],
    sizes: ["PP", "P", "M", "G", "GG"],
    stock: 54,
    imageBg: "radial-gradient(circle at 30% 30%,#a78cff,#311b45 60%,#0a0a12)",
    imageLabel: "kit orsa femme",
    desc: "Camisa principal Orsa em modelagem feminina. Gola redonda com ribana contrastante e recortes laterais ajustados.",
  },
];

const ORDERS = [
  {
    id: "STD-2026-08172",
    placedAt: "06 Mai 2026",
    status: "in_transit",
    statusLabel: "A caminho",
    eta: "Chega 09 Mai",
    total: 1748.8,
    tracking: "BR931748290392ST",
    items: [
      { id: "p01", qty: 1, size: "M", color: "Onyx" },
      { id: "p02", qty: 1, size: "42", color: "Glacier" },
    ],
    timeline: [
      { ts: "06/05 14:22", label: "Pedido confirmado", done: true },
      { ts: "06/05 19:08", label: "Pagamento aprovado", done: true },
      { ts: "07/05 10:14", label: "Em separação", done: true },
      { ts: "07/05 22:31", label: "Saiu para entrega", done: true },
      { ts: "09/05", label: "Entrega prevista", done: false },
    ],
  },
  {
    id: "STD-2026-07984",
    placedAt: "28 Abr 2026",
    status: "delivered",
    statusLabel: "Entregue",
    eta: "Entregue 02 Mai",
    total: 538.9,
    tracking: "BR918273645501ST",
    items: [
      { id: "p04", qty: 1, size: "G", color: "Crimson" },
      { id: "p05", qty: 1, size: "M", color: "Stone" },
      { id: "p06", qty: 1, size: "39-42", color: "Volt" },
    ],
    timeline: [
      { ts: "28/04 09:41", label: "Pedido confirmado", done: true },
      { ts: "28/04 11:02", label: "Pagamento aprovado", done: true },
      { ts: "29/04 16:48", label: "Saiu para entrega", done: true },
      { ts: "02/05 15:13", label: "Entregue", done: true },
    ],
  },
  {
    id: "STD-2026-07112",
    placedAt: "12 Abr 2026",
    status: "delivered",
    statusLabel: "Entregue",
    eta: "Entregue 16 Abr",
    total: 1758.0,
    tracking: "BR776655443210ST",
    items: [
      { id: "p07", qty: 1, size: "10", color: "Inferno" },
      { id: "p08", qty: 1, size: "M", color: "Onyx" },
      { id: "p11", qty: 1, size: "único", color: "Glacier" },
    ],
    timeline: [
      { ts: "12/04 22:11", label: "Pedido confirmado", done: true },
      { ts: "12/04 22:14", label: "Pagamento aprovado", done: true },
      { ts: "13/04 08:39", label: "Em separação", done: true },
      { ts: "14/04 13:21", label: "Saiu para entrega", done: true },
      { ts: "16/04 10:41", label: "Entregue", done: true },
    ],
  },
];

const ADDRESSES = [
  {
    id: "a1",
    label: "Casa",
    name: "Rafael Bastos",
    street: "Rua Tupinambás, 412 — Apto 1106",
    district: "Vila Madalena",
    city: "São Paulo",
    state: "SP",
    zip: "05435-040",
    phone: "(11) 9 8421-7733",
    primary: true,
  },
  {
    id: "a2",
    label: "Trabalho",
    name: "Rafael Bastos",
    street: "Av. Faria Lima, 3500 — 14º andar",
    district: "Itaim Bibi",
    city: "São Paulo",
    state: "SP",
    zip: "04538-132",
    phone: "(11) 9 8421-7733",
    primary: false,
  },
];

const FAQ = [
  { q: "Qual o prazo de entrega?", a: "Para capitais 1–3 dias úteis via STADIA Express. Demais regiões 3–7 dias úteis." },
  { q: "Posso trocar tamanho?", a: "Sim, dentro de 30 dias da entrega, sem custo de frete reverso na primeira troca." },
  { q: "As camisas são oficiais?", a: "Todas as licenciadas vêm com selo holográfico de autenticidade no peito." },
];

const REVIEWS = [
  { id: "r1", name: "Léo M.", date: "há 4 dias", rating: 5, body: "Caimento absurdo. Material super respirável, joguei com 32º e segurou bem.", verified: true },
  { id: "r2", name: "Carla T.", date: "há 1 semana", rating: 5, body: "Cor bate igualzinho. O tricot do peito dá um acabamento premium que não tinha visto em outras camisas.", verified: true },
  { id: "r3", name: "Diego F.", date: "há 2 semanas", rating: 4, body: "Veste justo — peguei um número acima do habitual. Qualidade impecável.", verified: false },
];

window.STADIA_DATA = { TEAMS, CATEGORIES, PRODUCTS, ORDERS, ADDRESSES, FAQ, REVIEWS };
